#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

DIR="$HOME/.config/herbstluftwm"
SCRIPTS="$HOME/.config/herbstluftwm/scripts"

### Resetting Hooks
hc emit_hook reload

hc keyunbind --all

# bash "$SCRIPTS"/xtwm_common
bash "$HOME"/.config/startup/herbs_startup

Mod5=Mod5                     # Hyper key
Mod1=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# tags
tag_names=( {1..9} )
# tag_names=( one two three four five six seven eight nine ten )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
	hc keybind "$Mod-$key" use ${tag_names[$i]}
        hc keybind "$Mod-Shift-$key" move_index "$i"
        hc keybind "$Mod-Control-$key" chain , move_index "$i" , use_index "$i"
    fi
done

hc keybind $Mod-Control-End chain , move '■' , use '■' # mv & go2 scratch-tag
hc keybind $Mod-Shift-End move '■' # mv client to scratch-tag
hc keybind $Mod-0 use '■'    	# g2 scratch-tagf

KP_keys=(KP_End KP_Down KP_Next KP_Left KP_Begin KP_Right KP_Home KP_Up KP_Prior)
for i in "${!tag_names[@]}"; do
    hc keybind "$Mod-${KP_keys[$i]}" use "${tag_names[$i]}"
done


hc keybind $Mod-q close_or_remove
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-r remove
hc keybind $Mod-Shift-r reload

### scratchpads ###
hc keybind $Mod-Home spawn $SCRIPTS/scratchpad.sh "■" "956x1046+2+27"      # Left Side scratchpad
# hc keybind $Mod-Home spawn $SCRIPTS/scratchpad.sh "■" "956x1046+957+27"  # Right Side scratchpad
hc keybind $Mod-End spawn $SCRIPTS/scratchpad.sh "■" "1358x760+281+170"    # Wide scratchpad

# for i in F1 F2 F3 F4; do
# 	hc keybind $Mod-Shift-$i spawn $DIR/reference/shivamsani/add_scratchpad.sh $i "Remove"
# 	hc keybind $Mod-$i spawn $DIR/reference/shivamsani/add_scratchpad.sh $i "Add"
# done

for i in F1 F2 F3 F4; do
    hc keybind $Mod5-Shift-$i spawn $SCRIPTS/add_scratchpad.sh $i "Remove"
    hc keybind $Mod5-$i spawn $SCRIPTS/add_scratchpad.sh $i "Add"
done


# multimedia #   --> F keys
hc keybind $Mod-F8 spawn Tor-browser
hc keybind XF86Mail spawn thunderbird
hc keybind $Mod-F9 spawn qbittorrent
hc keybind $Mod-F10 spawn calibre

hc keybind $Mod1-F7 spawn playerctl play-pause


# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod+Mod1+h   split   left    0.5
hc keybind $Mod+Mod1+j   split   bottom  0.5
hc keybind $Mod+Mod1+k   split   top     0.5
hc keybind $Mod+Mod1+l   split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# cycle through tags

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

hc keybind $Mod-apostrophe spawn $SCRIPTS/hc_non_empty next
hc keybind $Mod-semicolon  spawn $SCRIPTS/hc_non_empty prev

hc keybind $Mod-Page_Down use_index +1 --skip-visible
hc keybind $Mod-Page_Up  use_index -1 --skip-visible

# hc keybind $Mod-BackSpace use_previous
hc keybind $Mod-BackSpace chain , use_previous            \
   , try sprintf BODY "Tag: %s" clients.focus.tag         \
   spawn notify-send -a "ignore" -t 600 -r 300 -i ~/.config/herbstluftwm/assets/Hlwm_logo.svg BODY HLWM



hc keybind $Mod-Shift-period chain , move_index +1 , use_index +1
hc keybind $Mod-Shift-comma chain , move_index -1 , use_index -1



# layouting
# hc keybind $Mod-r remove
hc keybind $Mod-Shift-f floating toggle  # Entire frame
hc keybind $Mod-f set_attr clients.focus.floating toggle # Just the focused window

hc keybind $Mod-m fullscreen toggle

# hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle

hc keybind $Mod-i set_attr clients.focus.minimized true
hc keybind $Mod-Shift-i jumpto last-minimized

hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# hc keybind $Mod-space                                       \
    # or , and . compare tags.focus.curframe_wcount = 2        \
    # . cycle_layout +1 horizontal max vertical grid           \
    # , cycle_layout +1

### Cycle through the given layouts
hc keybind $Mod-space cycle_layout +1 max vertical horizontal

# focus
# hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

hc keybind $Mod-g cycle
# hc keybind $Mod1-grave cycle +1
# hc keybind $Mod1-Shift-grave cycle

hc keybind $Mod-u jumpto urgent

hc keybind $Mod-o rotate
hc keybind $Mod-Shift-o mirror both


# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# hc chain , load 8 '(clients max:0)' , load 9 '(clients max:0)' # max layout as default on tags 8 & 9
hc chain , attr tags.7.tiling.root.algorithm max , attr tags.8.tiling.root.algorithm max

# KEYBINDINGS ######################################################

# theme

hc set focus_stealing_prevention off

hc set focus_follows_mouse true

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
#----------------------------------

hc set frame_border_active_color '#222222cc' # #222222
hc set frame_border_normal_color '#101010cc' # #101010

# hc set frame_bg_normal_color '#7d7d7daa'
# hc set frame_bg_active_color '#565656aa'
hc set frame_bg_normal_color '#565656cc' # #565656
hc set frame_bg_active_color '#345F0Ccc' # #345F0C
#----------------------------------

hc set frame_border_width 1
# hc set frame_border_inner_width 0
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_normal_opacity 50	# Unfocused frame opacity in percent
hc set frame_active_opacity 50	# Focused frame opacity in percent
hc set frame_bg_transparent off
hc set frame_transparent_width 2
hc set frame_gap 2

hc attr theme.title_align center
hc attr theme.title_height 13
hc attr theme.title_when one_tab # only with the max layout
hc attr theme.title_font 'Iosevka Extended:pixelsize=12:weight=semibold'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 1  # space below the title's baseline

hc attr theme.outer_width 0
hc attr theme.inner_width 0

hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color white
#--------------------------------------
hc attr theme.active.color '#6495ed' # MAIN
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#323232'
hc attr theme.urgent.color '#fa8072'
hc attr theme.tab_color '#1F1F1F'
hc attr theme.active.tab_color '#323232'
hc attr theme.active.tab_outer_color '#565656'
hc attr theme.active.tab_title_color '#ababab'

hc attr theme.normal.title_color '#ffffff'
#---------------------------
hc attr theme.active.inner_color '#6495ed' # MAIN
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
#---------------------------

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
       attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#141414'

hc attr theme.active.padding_bottom 0
hc set window_gap 1
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# 
# RULES
hc unrule -F
hc rule switchtag=on

hc rule title=emacs-server focus=off tag=8

hc rule title='my_float_window' floating=on floatplacement=center floating_geometry=762x663+576+223

hc rule title='World' floating=on floatplacement=smart
hc rule title='Stepper' floating=on floatplacement=smart

hc rule title="your world program's event log" floating=on floatplacement=smart
hc rule title="your world program's state" floating=on floatplacement=smart

hc rule class=Localsend floating=on floatplacement=smart
hc rule class=Yad floatplacement=smart floating=on

hc rule class=TelegramDesktop tag=9
hc rule class=qBittorrent tag=9
hc rule class=calibre tag=9
hc rule class=Liferea tag=8
hc rule class=Thunderbird tag=8
hc rule title='Tor Browser' tag=8

hc rule class=Emacs title~'Emacs:emacs-everywhere' floating=on

hc rule class=ffplay floating=on
hc rule --class=pavucontrol floating=on floatplacement=center
hc rule --class=org.gnome.clocks floating=on floatplacement=center

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# hc rule --class=mpv floating=on floatplacement=center
hc rule floatplacement=center	# smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on


hc set default_frame_layout horizontal
hc set tree_style '╾│ ├└╼─┐'

# Empty frames function as the equivalent of BSPWM's receptacles: they
# receive the next client.  However, this only works for the focused
# tag.
hc rule index=e

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/scripts/hc-panel
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=~/.config/herbstluftwm/reference/hlwm.default/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

# http://thedarnedestthing.com/hooked%20on%20herbstluftwm
# layout icons: 󰓩  󰠵 
