
[bell]
animation = "EaseOutExpo"
duration = 0
# "window.opacity" = 1.0

[colors]
draw_bold_text_with_bright_colors = true

# [env]
# TERM = "xterm"
#term = "xterm-256color"

[font]
size = 11.25

normal = { family = "Iosevka Term", style= "Medium"}
bold = { family = "Iosevka Term", style= "Bold"}
italic = { family = "Iosevka Term", style= "Italic"}
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
# [font.bold]
# family = "Iosevka Term Extended"
# style = "Bold"

# [font.glyph_offset]
# x = 0
# y = 0

# [font.italic]
# family = "Iosevka Term Extended"
# style = "Italic"

# [font.normal]
# family = "Iosevka Term Medium Extended"
# style = "Medium"

# [font.offset]
# x = 0
# y = 0


[mouse]
# faux_scrolling_lines = 1
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# launcher = "open"

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
# "window.dynamic_title" = true

[window]
decorations = "none"

# [window.dimensions]
# columns = 100
# lines = 24

[window.padding]
x = 10
y = 10

[general]


# "cursor.style" = "Block"
# "debug.render_timer" = false
live_config_reload = true
import = [
# Dark
# "~/.config/alacritty/themes/themes/base16_default_dark.toml"
# "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"

# "~/.config/alacritty/themes/themes/rose-pine.toml"
# "~/.config/alacritty/themes/themes/solarized_osaka.toml"
# "~/.config/alacritty/themes/themes/solarized_dark.toml"
# "~/.config/alacritty/themes/themes/tomorrow_night.toml"
# "~/.config/alacritty/themes/themes/inferno.toml" #orange
# "~/.config/alacritty/themes/themes/oceanic_next.toml" #orange

# Light
# "~/.config/alacritty/themes/themes/papercolor_light.toml"
# "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
# "~/.config/alacritty/themes/themes/solarized_light.toml"

"~/.config/alacritty/my-themes/uk-kaolin-light.toml"
	#"~/.config/alacritty/my-themes/kaolin-dark.toml"
# "~/.config/alacritty/my-themes/modus-operandi-tinted.toml"
# "~/.config/alacritty/my-themes/modus-operandi.toml"
#"~/.config/alacritty/themes/themes/citylights.toml"
]
