
[bell]
animation = "EaseOutExpo"
duration = 0
# "window.opacity" = 1.0

[colors]
draw_bold_text_with_bright_colors = true

# [env]
# TERM = "xterm"

[font]
size = 10

[font.bold]
family = "Iosevka Extended"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Extended"
style = "Italic" 

[font.normal]
family = "Iosevka Semibold Extended"
style = "Semibold"

[font.offset]
x = 0
y = 0


[mouse]
# faux_scrolling_lines = 1
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# launcher = "open"

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
# "window.dynamic_title" = true

[window]
decorations = "none"

# [window.dimensions]
# columns = 100
# lines = 24

[window.padding]
x = 7
y = 7

[general]


# "cursor.style" = "Block"
# "debug.render_timer" = false
live_config_reload = true
import = [
# Dark
# "~/.config/alacritty/themes/themes/base16_default_dark.toml"
# "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"

# "~/.config/alacritty/themes/themes/rose-pine.toml"
# "~/.config/alacritty/themes/themes/solarized_osaka.toml"
# "~/.config/alacritty/themes/themes/tomorrow_night.toml"
"~/.config/alacritty/themes/themes/citylights.toml"
# "~/.config/alacritty/themes/themes/inferno.toml" #orange

# Light
# "~/.config/alacritty/themes/themes/papercolor_light.toml"
# "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
# "~/.config/alacritty/themes/themes/solarized_light.toml"

]
