backend = "glx"
shadow = false;
fading = false;
opacity = false;
blur-background = false

# Rule-based per-window options.
#
# See WINDOW RULES section in the man page for how these work.
rules: (
{
   match = "class_g = 'Emacs' && !focused        || "
           "class_g = 'qutebrowser' && !focused  || "
           "class_g = 'Thunar' && !focused";
           # "class_g = 'Navigator' && !focused";
   dim = 0.1;
}
)
