Gdk/WindowScalingFactor 1
Gtk/ButtonImages 1
Gtk/CanChangeAccels 0
Gtk/ColorPalette "black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"
Gtk/CursorThemeName "Bibata-Modern-Ice" # CHANGED
Gtk/CursorThemeSize 18
Gtk/DecorationLayout "icon,menu:minimize,maximize,close"
Gtk/DialogsUseHeader 0
Gtk/FontName "Noto Sans 10"
Gtk/IconSizes ""
Gtk/KeyThemeName ""
Gtk/MenuBarAccel ""
Gtk/MenuImages 1
Gtk/MonospaceFontName "Monospace 10"
Gtk/TitlebarMiddleClick "lower"
Gtk/ToolbarIconSize 3
Gtk/ToolbarStyle "icons"

Net/CursorBlink 1
Net/CursorBlinkTime 1200
Net/CursorThemeName "Bibata-Modern-Ice" # CHANGED
Net/CursorThemeSize 18
Net/DndDragThreshold 8
Net/DoubleClickDistance 5
Net/DoubleClickTime 400
Net/EnableEventSounds 1
Net/EnableInputFeedbackSounds 1
Net/IconThemeName "Papirus-Dark" # CHANGED
Net/SoundThemeName "default"
Net/ThemeName "Nordic-darker"   # CHANGED

Xft/Antialias 1
Xft/DPI 98304
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
