;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #141C21
; background = #aa141C21          ; trasnparent
; foreground = #93A1A1
foreground = #FFFFFF
sep = #3C4449

shade1 = #BF360C
shade2 = #D84315
shade3 = #E64A19
shade4 = #F4511E
shade5 = #FF5722
shade6 = #FF7043
shade7 = #FF8A65
shade8 = #FFAB91

 white = #FFFFFF
 black = #0a0a0a


 red = #EC7875
 pink = #EC407A
 purple = #BA68C8
 blue = #42A5F5
 cyan = #4DD0E1
 teal = #00B19F
 green = #61C766
 lime = #B9C244
 yellow = #FDD835
 amber = #FBC02D
 orange = #E57C46
 brown = #AC8476
 indigo = #6C77BB
 gray = #9E9E9E
 blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_