#!/bin/sh

# Variable Defaulting
: "${DBUS_SESSION_BUS_ADDRESS:=unix:path=/run/user/$(id -u)/bus}"

# Remove the environment file when the service stops/fails
rm -f "$TURNSTILE_ENV_DIR/DBUS_SESSION_BUS_ADDRESS"
