module Doc.Help where
import XMonad

myHelp :: String
myHelp = unlines ["Modifier key is 'Super'. My keybindings:",
    "",
    "-- launching and killing programs",
    "Mod-Enter        Main Terminal (tmux+urxvtc)",
    "Mod-a            Rofi Application Launch",
    "Mod-s            Rofi Scripts Menu",
    "Mod-q            Close/kill the focused window",
    "mod-Space        Rotate Layout algorithms (Tall, Tabs, MTall)",
    "mod-Shift-Space  Reset the layout to default",
    "Mod-n            Resize/refresh viewed windows to the correct size",
    "Mod-Shift-/      Show this help message with the default keybindings",
    "",
    "-- move focus up or down the window stack",
    "mod-Tab        Move focus to the next window",
    "mod-Shift-Tab  Move focus to the previous window",
    "Mod-j          Move focus to the next window",
    "Mod-k          Move focus to the previous window",
    "Mod-m          Move focus to the master window",
    "",
    "-- modifying the window order",
    "Mod-Shift-m   Swap the focused window and the master window",
    "mod-Shift-j  Swap the focused window with the next window",
    "mod-Shift-k  Swap the focused window with the previous window",
    "",
    "-- resizing the master/slave ratio",
    "mod-h  Shrink the master area",
    "mod-l  Expand the master area",
    "",
    "-- floating layer support",
    "Mod-t        Push window back into tiling; unfloat and re-tile it",
    "Mod-Shift-t  Toggle Floating status",
    "",
    "-- increase or decrease number of windows in the master area",
    "Mod-Comma  (mod-,)   Switch to Previous WS",
    "Mod-Period (mod-.)   Switch to Next WS",
    "Mod-Shift-Comma      Switch to Previous Non-Empty WS",
    "Mod-Shift-Period     Switch to Next Non-Empty WS",
    "Mod-Control-Comma    Switch to Previous Empty WS",
    "Mod-Control-Period   Switch to Next Empty WS",
    "",
    "-- quit, or restart",
    "mod-Shift-q  Quit xmonad",
    "mod-q        Restart xmonad",
    "mod-[1..9]   Switch to workSpace N",
    "",
    "-- Workspaces & screens",
    "mod-[1..9]         Move to workspace N",
    "mod-Shift-[1..9]   Move client to workspace N",
    "mod-{w,e,r}        Switch to physical/Xinerama screens 1, 2, or 3",
    "mod-Shift-{w,e,r}  Move client to screen 1, 2, or 3",
    "",
    "-- Mouse bindings: default actions bound to mouse events",
    "mod-button1  Set the window to floating mode and move by dragging",
    "mod-button2  Raise the window to the top of the stack",
    "mod-button3  Set the window to floating mode and resize by dragging"]
