#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

ASSETS="$HOME/.config/herbstluftwm/assets"
current_tag=$(( $(hc attr tags.focus.index) + 1 ))
my_tags=($(hc tag_status | grep -oP '[#\:\-\!]\K\d+'))
length=${#my_tags[@]}

notify() {
    dunstify -a "ignore" -t 600 -r 234 -i "$ASSETS/$1.png" Tag
}

next_tag() {
    for ((i = 0; i < $length; i++)); do
        if [[ ${my_tags[i]} -eq $current_tag ]]; then
            # Calculate the next index, wrap around if needed
            next_index=$(( (i + 1) % $length ))
        fi
    done
    tag=${my_tags[next_index]}
    hc use $tag
    notify $tag

}

prev_tag() {
    for ((i = 0; i < $length; i++)); do
        if [[ ${my_tags[i]} -eq $current_tag ]]; then
            # Calculate the previous tag, wrap around if needed
            prev_index=$(( (i - 1 + $length) % $length ))
        fi
    done
    tag=${my_tags[prev_index]}
    hc use $tag
    notify $tag
}

# Check for argument
if [ -z "$1" ]; then
    echo "No argument provided. use 'prev' or 'next' as args"
    exit 1
fi

# Run the appropriate function based on the argument
case $1 in
    next)
        next_tag
        ;;
    prev)
        prev_tag
        ;;
    *)
        echo "Invalid argument. use 'prev' or 'next' as args"
        exit 1
        ;;
esac
