[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #FFFFFF
foreground = #000000
sep = #F2F2F2


 red = #A60000
 pink = #7B435C
 purple = #BA68C8
 blue = #0031a9
 cyan = #005e8b
 teal = #00B19F
 green = #006800
 lime = #B9C244
 yellow = #6f5500
 amber = #FBC02D
 orange = #ff8f88
 brown = #AC8476
 indigo = #4a3a8a
 gray = #9E9E9E
 blue-gray = #6D8895
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
